name: Zip Directory and Publish Release

on:
  push:
    # Avoid using all the resources/limits available by checking only
    # relevant branches and tags. Other branches can be checked via PRs.
    branches: [main]
    tags: ["v[0-9]*", "[0-9]+.[0-9]+*"] # Match tags that resemble a version
  workflow_dispatch: # Allow manually triggering the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Archive Release Zip
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'release.zip'
        path: 'ctags.d'
    - name: Archive Release Tar
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'tar'
        filename: 'release.tar.gz'
        path: 'ctags.d'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip,release.tar.gz"
        # token: ${{ secrets.GITHUB_TOKEN }}
