name: Zip Directory and Publish Release

on:
  push:
    # Avoid using all the resources/limits available by checking only
    # relevant branches and tags. Other branches can be checked via PRs.
    branches: [main]
    tags: ["v[0-9]*", "[0-9]+.[0-9]+*"] # Match tags that resemble a version
  workflow_dispatch: # Allow manually triggering the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        path: 'ctags.d'
        exclusions: '*.git* /*node_modules/* .editorconfig'
